apiVersion: kuttl.dev/v1beta1
kind: TestSuite
artifactsDir: ./tests/_build/artifacts/
testDirs:
  - ./tests/modified/sidecar/
  - ./tests/modified/operator/
timeout: 150
parallel: 4
startKIND: true
kindNodeCache: true
kindContainers:
  - registry.localhost:5000/sumologic/tailing-sidecar-operator:test
  - registry.localhost:5000/sumologic/tailing-sidecar:test
commands: 
  - command: helm upgrade --install test-release ./helm/tailing-sidecar-operator -f ./helm/tests/values.withCustomConfiguration.yaml -n tailing-sidecar-system --create-namespace
  - command: kubectl wait --for=condition=available --timeout 300s deploy -l app.kubernetes.io/name=tailing-sidecar-operator -n tailing-sidecar-system
  - command: kubectl wait --for=condition=ready --timeout 300s pod -l app.kubernetes.io/name=tailing-sidecar-operator -n tailing-sidecar-system
