apiVersion: kuttl.dev/v1beta1
kind: TestSuite
artifactsDir: ./tests/_build/artifacts/
testDirs:
  - ./tests/sidecar/
  - ./tests/operator/
timeout: 150
parallel: 4
startKIND: true
kindNodeCache: true
kindContainers:
  - registry.localhost:5000/sumologic/tailing-sidecar-operator:test
  - registry.localhost:5000/sumologic/sidecar:test
commands: 
  - command: make -C ./operator deploy-cert-manager
  - command: helm upgrade --install test-release ./helm/tailing-sidecar-operator -f ./helm/tests/values.withCertManager.yaml -n tailing-sidecar-system --create-namespace
  - command: make e2e-wait-until-operator-ready
