# permissions for end users to view tailingsidecars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailingsidecar-viewer-role
rules:
- apiGroups:
  - tailing-sidecar.sumologic.com
  resources:
  - tailingsidecarconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tailing-sidecar.sumologic.com
  resources:
  - tailingsidecarconfigs/status
  verbs:
  - get
