# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: otelcol-sidecar

env:
  - GHCR_IMAGE={{ if index .Env "GHCR_IMAGE" }}{{ .Env.GHCR_IMAGE }}{{ else }}ghcr.io/sumologic/tailing-sidecar-otel{{ end }}
  - ECR_IMAGE={{ if index .Env "ECR_IMAGE" }}{{ .Env.ECR_IMAGE }}{{ else }}public.ecr.aws/sumologic/tailing-sidecar-otel{{ end }}
  - DOCKERHUB_IMAGE={{ if index .Env "DOCKERHUB_IMAGE" }}{{ .Env.DOCKERHUB_IMAGE }}{{ else }}sumologic/tailing-sidecar-otel{{ end }}

before:
  hooks:
    - make generate-sources VERSION={{ .Version }}

builds:
  - dir: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

# disable archiving
archives:
  - format: binary

dockers:
  - image_templates:
      - "{{ .Env.ECR_IMAGE }}:{{ .Version }}-amd64"
      - "{{ .Env.ECR_IMAGE }}:main-amd64"
      - "{{ .Env.GHCR_IMAGE }}:{{ .Version }}-amd64"
      - "{{ .Env.GHCR_IMAGE }}:main-amd64"
      - "{{ .Env.DOCKERHUB_IMAGE }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKERHUB_IMAGE }}:main-amd64"
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - "config.yaml"
  - image_templates:
      - "{{ .Env.ECR_IMAGE }}:{{ .Version }}-arm64"
      - "{{ .Env.ECR_IMAGE }}:main-arm64"
      - "{{ .Env.GHCR_IMAGE }}:{{ .Version }}-arm64"
      - "{{ .Env.GHCR_IMAGE }}:main-arm64"
      - "{{ .Env.DOCKERHUB_IMAGE }}:{{ .Version }}-arm64"
      - "{{ .Env.DOCKERHUB_IMAGE }}:main-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
    extra_files:
      - "config.yaml"

docker_manifests:
  - name_template: "{{ .Env.GHCR_IMAGE }}:{{ .Version }}"
    image_templates:
      - "{{ .Env.GHCR_IMAGE }}:{{ .Version }}-amd64"
      - "{{ .Env.GHCR_IMAGE }}:{{ .Version }}-arm64"
  - name_template: "{{ .Env.GHCR_IMAGE }}:main"
    image_templates:
      - "{{ .Env.GHCR_IMAGE }}:main-amd64"
      - "{{ .Env.GHCR_IMAGE }}:main-arm64"
  - name_template: "{{ .Env.ECR_IMAGE }}:{{ .Version }}"
    image_templates:
      - "{{ .Env.ECR_IMAGE }}:{{ .Version }}-amd64"
      - "{{ .Env.ECR_IMAGE }}:{{ .Version }}-arm64"
  - name_template: "{{ .Env.ECR_IMAGE }}:main"
    image_templates:
      - "{{ .Env.ECR_IMAGE }}:main-amd64"
      - "{{ .Env.ECR_IMAGE }}:main-arm64"
  - name_template: "{{ .Env.DOCKERHUB_IMAGE }}:{{ .Version }}"
    image_templates:
      - "{{ .Env.DOCKERHUB_IMAGE }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKERHUB_IMAGE }}:{{ .Version }}-arm64"
  - name_template: "{{ .Env.DOCKERHUB_IMAGE }}:main"
    image_templates:
      - "{{ .Env.DOCKERHUB_IMAGE }}:main-amd64"
      - "{{ .Env.DOCKERHUB_IMAGE }}:main-arm64"

# we only want to build and publish docker images
release:
  disable: true
