dist:
  name: otelcol-sidecar
  description: Sumo Logic OpenTelemetry Collector Sidecar distribution
  # the module name for the new distribution, following Go mod conventions. Optional, but recommended.
  module: github.com/SumoLogic/tailing-sidecar/sidecar
  # the OpenTelemetry Collector version to use as base for the distribution.
  otelcol_version: 0.137.0
  # the path to write the output (sources and binary).
  output_path: ./cmd

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.137.0

# Note: These components aren't strictly necessary, but they don't measurably increase the binary size
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.137.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.137.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor v0.137.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.137.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.137.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.137.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/encoding/textencodingextension v0.137.0
