apiVersion: tailing-sidecar.sumologic.com/v1
kind: TailingSidecarConfig
metadata:
  name: tailingsidecar-sample
spec:
  annotationsPrefix: tailing-sidecar.sumologic.com
  podSelector:
    matchLabels:
      tailing-sidecar: "true"
  configs:
    sidecar-2:
      volumeMount: 
        name: varlogconfig
        mountPath: /varconfig-new-dir/log
      path: /varconfig-new-dir/log/example2.log
      annotations:
        sourceCategory: sourceCategory-2
        annotation-2: "true"
