fullnameOverride: ""
nameOverride: ""

operator:
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/sumologic/tailing-sidecar-operator
    tag: 0.3.0
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi

sidecar:
  image:
    repository: ghcr.io/sumologic/tailing-sidecar
    tag: 0.3.0

# Configuration for MutatingWebhook which is used by tailing sidecar operator
# for details please see Kubernetes API Reference Docs
# e.g. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#mutatingwebhookconfiguration-v1-admissionregistration-k8s-io
webhook:
  failurePolicy: Ignore
  reinvocationPolicy: IfNeeded
  
  objectSelector: {}
    # matchLabels:
    #   tailing-sidecar: "true"

  namespaceSelector: {}
    # matchLabels:
    #   tailing-sidecar: "true"

certManager:
  enabled: false
