fullnameOverride: ""
nameOverride: ""

operator:
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/sumologic/tailing-sidecar-operator
    tag: 0.1.0
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi

sidecar:
  image:
    repository: ghcr.io/sumologic/tailing-sidecar
    tag: 0.1.0

certManager:
  enabled: false
