fullnameOverride: ""
nameOverride: ""

operator:
  image:
    pullPolicy: IfNotPresent
    repository: public.ecr.aws/sumologic/tailing-sidecar-operator
    tag: 0.0.0
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi

sidecar:
  image:
    repository: public.ecr.aws/sumologic/tailing-sidecar
    tag: 0.0.0
