fullnameOverride: ""
nameOverride: ""

operator:
  image:
    pullPolicy: IfNotPresent
    repository: public.ecr.aws/sumologic/tailing-sidecar-operator
    # Overrides the image tag whose default is the Helm Chart appVersion.
    tag: ""
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi

  ## Enable leader election mechanism for protecting against split brain if multiple operator pods/replicas are started.
  ## See more at https://docs.openshift.com/container-platform/4.10/operators/operator_sdk/osdk-leader-election.html
  leaderElection:
    enabled: true
    leaseDuration: "137s"
    renewDeadline: "107s"
    retryPeriod: "26s"

  livenessProbe: {}
    # initialDelaySeconds: 1
    # periodSeconds: 20
  startupProbe: {}
    # periodSeconds: 3

sidecar:
  image:
    repository: public.ecr.aws/sumologic/tailing-sidecar
    # Overrides the image tag whose default is the Helm Chart appVersion.
    tag: ""
  # Configuration for sidecar compute resource requirements.
  # Those are the default resources settings and can be overrides by TailingSidecarConfig
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi

kubeRbacProxy:
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/brancz/kube-rbac-proxy
    tag: v0.11.0

# Configuration for MutatingWebhook which is used by tailing sidecar operator
# for details please see Kubernetes API Reference Docs
# e.g. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#mutatingwebhookconfiguration-v1-admissionregistration-k8s-io
webhook:
  failurePolicy: Ignore
  reinvocationPolicy: Never
  
  objectSelector: {}
    # matchLabels:
    #   tailing-sidecar: "true"

  namespaceSelector: {}
    # matchLabels:
    #   tailing-sidecar: "true"

certManager:
  enabled: false

scc:
  create: true
