fullnameOverride: ""
nameOverride: ""

operator:
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/sumologic/tailing-sidecar-operator
    # Overrides the image tag whose default is the Helm Chart appVersion.
    tag: ""
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi
  livenessProbe: {}
    # initialDelaySeconds: 1
    # periodSeconds: 20
  startupProbe: {}
    # periodSeconds: 3

sidecar:
  image:
    repository: ghcr.io/sumologic/tailing-sidecar
    # Overrides the image tag whose default is the Helm Chart appVersion.
    tag: ""

kubeRbacProxy:
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/brancz/kube-rbac-proxy
    tag: v0.11.0

# Configuration for MutatingWebhook which is used by tailing sidecar operator
# for details please see Kubernetes API Reference Docs
# e.g. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#mutatingwebhookconfiguration-v1-admissionregistration-k8s-io
webhook:
  failurePolicy: Ignore
  reinvocationPolicy: Never
  
  objectSelector: {}
    # matchLabels:
    #   tailing-sidecar: "true"

  namespaceSelector: {}
    # matchLabels:
    #   tailing-sidecar: "true"

certManager:
  enabled: false

scc:
  create: true
