apiVersion: tailing-sidecar.sumologic.com/v1
kind: TailingSidecarConfig
metadata:
  name: tailingsidecar-sample
  namespace: tailing-sidecar-system
spec:
  annotationsPrefix: tailing-sidecar.sumologic.com
  podSelector:
    matchLabels:
      tailing-sidecar-resource: "true"
  configs:
    sidecar-1:
      volumeMount:
        name: varlog
        mountPath: /var/log
      path: /var/log/example0.log
      annotations:
        sourceCategory: sourceCategory-2
        annotation-2: "true"
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
